if ITrack == nil then ITrack = {} end

-- BDD of dungeons difficulty
-- BDD of raids difficulty
--ITrack.raids_difficulty = {
--  [14] = "Normal",
--  [15] = "Heroic",
--  [16] = "Mythic",
--}

-- Devourer
table.insert(ITrack.defaults.profile.debuffs_table , 2128,{
  -- Normal
  [14] = {
    -- ????
    [262314] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    }, 
  },
  -- Heroic
  [15] = {
    -- ????
    [262314] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    }, 
  },
  -- Mythic
  [16] = {
    -- ????
    [262314] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    }, 
  },
})

-- Ghuun
table.insert(ITrack.defaults.profile.debuffs_table , 2122,{
  -- Normal
  [14] = {
    -- ???
    [272506] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [263227] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [263235] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [263420] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    }, 
    -- ???
    [263436] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [267409] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
  },
  -- Heroic
  [15] = {
    -- ???
    [272506] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [263235] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [263227] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [263420] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [263436] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [267409] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
  },
  -- Mythic
  [16] = {
    -- ???
    [263436] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [272506] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [268074] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [267813] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [263420] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [263227] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [267409] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [263235] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [277007] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
  },
})

-- Mother
table.insert(ITrack.defaults.profile.debuffs_table , 2141,{
  -- Normal
  [14] = {
    -- Tank
    [267787] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [279661] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [279663] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [268198] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
  },
  -- Heroic
  [15] = {
    -- Tank
    [267787] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [279661] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [279663] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [268198] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
  },
  -- Mythic
  [16] = {
    -- Tank
    [267787] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [279661] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [279663] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [268198] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
  },
})

-- Mythrax
table.insert(ITrack.defaults.profile.debuffs_table , 2135,{
  -- Normal
  [14] = {
    -- TAnk
    [274693] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [279013] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [272541] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [272407] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [272146] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
  },
  -- Heroic
  [15] = {
    -- TAnk
    [274693] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [279013] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [272541] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [272407] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [272146] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
  },
  -- Mythic
  [16] = {
    -- TAnk
    [274693] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [279013] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [272541] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [272407] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [272146] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
  },
})

-- Taloc
table.insert(ITrack.defaults.profile.debuffs_table , 2144,{
  -- Normal
  [14] = {
    -- ???
    [271222] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [275270] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [275686] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
  },
  -- Heroic
  [15] = {
    -- ???
    [271222] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [275270] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [275686] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
  },
  -- Mythic
  [16] = {
    -- ???
    [271222] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [275270] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [275686] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [275189] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ???
    [275203] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
  },
})

-- Vectis
table.insert(ITrack.defaults.profile.debuffs_table , 2134,{
  -- Normal
  [14] = {
    -- Tank
    [265178] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ????
    [265127] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ????
    [267160] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ????
    [265212] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ????
    [266948] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
  },
  -- Heroic
  [15] = {
    -- Tank
    [265178] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ????
    [265127] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ????
    [267160] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ????
    [265212] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ????
    [266948] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
  },
  -- Mythic
  [16] = {
    -- Tank
    [265178] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ????
    [265127] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ????
    [267160] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ????
    [265212] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ????
    [266948] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ????
    [274990] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
  },
})

-- Zekvoz
table.insert(ITrack.defaults.profile.debuffs_table , 2136,{
  -- Normal
  [14] = {
    -- Tank
    [265237] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- Tank
    [265264] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ????
    [265363] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ????
    [265662] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
  },
  -- Heroic
  [15] = {
    -- Tank
    [265237] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- Tank
    [265264] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ????
    [265363] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ????
    [265662] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
  },
  -- Mythic
  [16] = {
    -- Tank
    [265237] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- Tank
    [265264] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ????
    [265363] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ????
    [265662] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
  },
})

--Zul
table.insert(ITrack.defaults.profile.debuffs_table , 2145,{
  -- Normal
  [14] = {
    -- Tank
    [274358] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ????
    [274358] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ????
    [273437] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ????
    [274195] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ????
    [276299] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
  },
  -- Heroic
  [15] = {
    -- Tank
    [274358] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ????
    [276299] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ????
    [274358] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ????
    [273437] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ????
    [274195] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
  },
  -- Mythic
  [16] = {
    -- Tank
    [274358] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ????
    [276299] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ????
    [274195] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ????
    [274358] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ????
    [273437] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ????
    [276434] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
    -- ????
    [276672] = {
      ["IfActive"] = false,
      ["PlayerOnly"] = "All",
      ["Count"] = 0,
      ["Type"] = "Classic",
      ["TypeDistance"] = 0,
      ["Rôle"] = "All",
      ["MaxStacks"] = true,
      ["MaxStacksNumber"] = 5,
      ["Columns"] = 1,
      ["Activate"] = true,
      ["Base"] = true,
    },
  },
})